# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean Build Test
      run:
      - xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" -sdk macosx -destination "platform=macOS" CODE_SIGNING_REQUIRED=NO
      - xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" -sdk iphonesimulator -destination "platform=iOS Simulator, OS=16.0" CODE_SIGNING_REQUIRED=NO
